### ISSUE TITLE
Add a drop item option

### ISSUE THREAD

**Issue by Yiwen7735** [Yiwen7735/Adventure_Game#26]
Takes a user input `d` that allows player to drop the items they have. Similar to the command for equip (`e`), it will also be followed by a further specification of the item to drop (e.g., `w#` & `o#`)

**Comment by d18r** [comment]
Should it be possible to pick up a dropped weapon from the room in which it was dropped?

**Comment by d18r** [comment]
Yes, it should be possible to pick up a dropped weapon.
